spring:
  profiles:
      active:
        - test

---
spring:
  profiles: dev
  application:
    name: spring-cloud-producer

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

---
spring:
  profiles: test
  application:
    name: spring-cloud-producer

server:
  port: 9010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/